### PR TITLE
Fix executions with assertions on circular objects

### LINKED ISSUE #193: Bridge's testEnd event handler is passing too much to sendMessage: JSON errors.
The testEnd handler in the chrome bridge is passing the entire `obj` argument, which must be serialized into JSON. But sometimes this object includes objects which cannot be serialized, such as complex objects with circular references, in which case it throws an error and halts testing.

```javascript
QUnit.on('testEnd', function(obj) {
	sendMessage('qunit.on.testEnd', obj);
});
```

A sample error:

```
>> Error: TypeError: Converting circular structure to JSON
>>     --> starting at object with constructor 'Foo'
>>     |     property 'bar' -> object with constructor 'Object'
>>     --- property 'foo' closes the circle
>>     at JSON.stringify (<anonymous>)
>>     at win.<computed> (<anonymous>:17:26)
>>     at sendMessage (<anonymous>:130:32)
>>     at Array.<anonymous> (<anonymous>:153:3)
```

Looking at the source code, it appears that there is no practical reason for sending up the entire object when only three properties are in use. I tested locally with the following and it seems to work well:

```javascript
QUnit.on('testEnd', function(obj) {
	sendMessage('qunit.on.testEnd', {
		status: obj.status,
		errors: obj.errors,
		fullName: obj.fullName,
	});
});
```

This appears to be the current pattern for the `runEnd` event for the sake or removing large, unused properties:

```javascript
QUnit.on('runEnd', function(obj) {
	// Re-create object to strip out large 'tests' field (deprecated).
	sendMessage('qunit.on.runEnd', {
		testCounts: obj.testCounts,
		runtime: obj.runtime,
		status: obj.status
	});
});
```

This bug appears to have been introduced by #189

### PR DESCRIPTION
**Pull request by vtintillier**
Fixes #193.

### CODE REVIEW

**Comment by Krinkle** [comment]
@vtintillier wrote at [issue 193](https://github.com/gruntjs/grunt-contrib-qunit/issues/193#issuecomment-1274285902):
> Created #195 , but no CLA prompt yet.

Looks like something stopped working. No problem, we can do it manully here.

> Developer's Certificate of Origin 1.1 <https://developercertificate.org/>
>
> By making a contribution to this project, I certify that:
>
> (a) The contribution was created in whole or in part by me and I
>     have the right to submit it under the open source license
>     indicated in the file; or
>
> (b) The contribution is based upon previous work that, to the best
>     of my knowledge, is covered under an appropriate open source
>     license and I have the right under that license to submit that
>     work with modifications, whether created in whole or in part
>     by me, under the same open source license (unless I am
>     permitted to submit under a different license), as indicated
>     in the file; or
>
> (c) The contribution was provided directly to me by some other
>     person who certified (a), (b) or (c) and I have not modified
>     it.
>
> (d) I understand and agree that this project and the contribution
>     are public and that a record of the contribution (including all
>     personal information I submit with it, including my sign-off) is
>     maintained indefinitely and may be redistributed consistent with
>     this project or the open source license(s) involved.

Please read the above and reply stating whether the above is true in your case. In a nut shell, we are asking whether you wrote the patch yourself and that you are able and willing to release it under the [MIT open-source license](https://github.com/gruntjs/grunt-contrib-qunit/blob/v6.2.0/LICENSE-MIT).

**Comment by vtintillier** [comment]
> Please read the above and reply stating whether the above is true in your case. In a nut shell, we are asking whether you wrote the patch yourself and that you are able and willing to release it under the MIT open-source license.

The above is true, I wrote the patch myself 👍

**Review by Krinkle — APPROVED** [review]

File: Gruntfile.js [hunk 1]
```diff
@@ -113,9 +127,16 @@ module.exports = function(grunt) {
...
       },
+      circularObject: {
+        command: 'grunt qunit:circularObject'
+      },
       failAssert: {
         command: 'grunt qunit:failAssert --with-failing'
       },
+      failCircularObject: {
+        command: 'grunt qunit:failCircularObject --with-failing',
+        maxBuffer: 1000 * 1000 * 1000
```
Comment (vtintillier) [inline Gruntfile.js:138]: I realized this was in fact not necessary, I only added this while trying to understand why my failure test was not working as I expected. I thought ouput was truncated, but it was only truncated in the debug console 🤦‍♂️

Removed it in #196
